apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ $.Release.Name }}-deploy
spec:
    replicas: {{ .Values.deploy.replicas }}
    selector:
        matchLabels:
            app: {{ $.Release.Name }}
    template:
      metadata:
        labels:
          app: {{ $.Release.Name }}
      spec:
        containers:
        - image: {{ .Values.deploy.image.name }}:{{ .Values.deploy.image.tag }}
          name: {{ .Values.deploy.containerName }}
          imagePullPolicy: {{ .Values.deploy.imagePullPolicy }}
          ports:
          - containerPort: {{ .Values.deploy.port }}
          env:
          {{- range .Values.deploy.env }}
          - name: {{ .Values.deploy.name }}
            value: {{ .value | quote }}
          {{- end }}
