jenkins:
  systemMessage: "Welcome to Jenkins configured with JCasC!"
  numExecutors: 1
  mode: NORMAL
  scmCheckoutRetryCount: 2

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"
          fullName: "Administrator"

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  clouds:
  - kubernetes:
          containerCapStr: "10"
          defaultsProviderTemplate: ""
          connectTimeout: "5"
          readTimeout: "15"
          jenkinsUrl: "http://release-name-jenkins.default.svc.cluster.local:8080"
          jenkinsTunnel: "release-name-jenkins-agent.default.svc.cluster.local:50000"
          maxRequestsPerHostStr: "32"
          retentionTimeout: "5"
          waitForPodSec: "600"
          name: "kubernetes"
          namespace: "default"
          serverUrl: "https://kubernetes.default"
          credentialsId: ""
          podLabels:
          - key: "jenkins/release-name-jenkins-agent"
                value: "true"
          templates:
                - name: "default"
                  namespace: "default"
                  id: 524cd9b170b8fbab8776abf9f16c71dacdff11335471721b0aa2253534fa86bd
                  containers:
                  - name: "jnlp"
                        alwaysPullImage: false
                        args: "^${computer.jnlpmac} ^${computer.name}"
                        envVars:
                          - envVar:
                                  key: "JENKINS_URL"
                                  value: "http://release-name-jenkins.default.svc.cluster.local:8080/"
                        image: "jenkins/inbound-agent:3206.vb_15dcf73f6a_9-3"
                        privileged: "false"
                        resourceLimitCpu: 512m
                        resourceLimitMemory: 512Mi
                        resourceRequestCpu: 512m
                        resourceRequestMemory: 512Mi
                        ttyEnabled: false
                        workingDir: /home/jenkins/agent
                  idleMinutes: 0
                  instanceCap: 2147483647
                  label: "release-name-jenkins-agent "
                  nodeUsageMode: "NORMAL"
                  podRetention: Never
                  showRawYaml: true
                  serviceAccount: "default"
                  slaveConnectTimeoutStr: "100"
                  yamlMergeStrategy: override
unclassified:
  location:
    adminAddress: "admin@jenkins.io"
    url: "http://jenkins:8080/"
