jenkins:
  systemMessage: "Welcome to Jenkins configured with JCasC!"
  numExecutors: 1
  mode: NORMAL
  scmCheckoutRetryCount: 2

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"
          fullName: "Administrator"

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

  tools:
    jdk:
      installations:
        - name: "OpenJDK 11"
          home: "/usr/lib/jvm/java-11-openjdk"

unclassified:
  location:
    adminAddress: "admin@jenkins.io"
    url: "http://jenkins:8080/"
