apiVersion: v1
kind: Service
metadata:
  name: memcached-service
spec:
  type: NodePort
  ports:
    - port: 11211
      targetPort: 11211
      nodePort: 31111
  selector:
    app: memcached

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memcached
  template:
    metadata:
      labels:
        app: memcached
    spec:
      containers:
        - name: memcached
          image: memcached:alpine
          ports:
            - containerPort: 11211
