apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: artifactory-custom
  namespace: staging
spec:
  interval: 1m
  chart:
    spec:
      chart: ./HelmCharts/artifactory_prod
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    artifactory:
      artifactory:
        service:
          type: NodePort
          nodePort: 30005