apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: grafana-custom
  namespace: staging
spec:
  interval: 1m
  chart:
    spec:
      chart: ./HelmCharts/grafana_prod
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    grafana:
      persistence:
        enabled: true
        existingClaim: "grafana-claim"
      service:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: grafana.powertrckr.com
          service.beta.kubernetes.io/aws-load-balancer-internal: "false"
        type: LoadBalancer