apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: jenkins-custom
  namespace: staging
spec:
  interval: 1m
  chart:
    spec:
      chart: ./HelmCharts/jenkins_prod
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    jenkins:
      persistence:
        enabled: true
        existingClaim: "jenkins-claim"
      controller:
        serviceType: NodePort
        nodePort: 30007
        agentListenerNodePort: 31113
        agentListenerServiceType: "NodePort"
        agentListenerPort: 31114
        admin:
          username: "admin"
          password: "password"
        installPlugins:
          - prometheus:763.vf8c26b_a_34b_d6
