apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: artifactory-custom
  namespace: staging
spec:
  interval: 1m
  chart:
    spec:
      chart: ./HelmCharts/artifactory_prod/artifactory
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    artifactory:
      persistence:
        enabled: true
        existingClaim: "artifactory-claim"
      service:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: artifactory.powertrckr.com
          service.beta.kubernetes.io/aws-load-balancer-internal: "false"
        type: LoadBalancer