apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: postgresql-custom
  namespace: staging
spec:
  interval: 1m
  chart:
    spec:
      chart: ./HelmCharts/postgresql_prod
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    postgresql:
      primary:
        persistence:
          enabled: true
          existingClaim: "postgresql-claim"
        service:
          annotations:
            external-dns.alpha.kubernetes.io/hostname: postgresql.powertrckr.com
            service.beta.kubernetes.io/aws-load-balancer-internal: "false"
          type: ClusterIP