apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prometheus-custom
  namespace: staging
spec:
  interval: 1m
  chart:
    spec:
      # Ścieżka do charta w repozytorium Git.
      # Warto zauważyć, że Flux wymaga referencji do źródła w postaci GitRepository lub HelmRepository.
      # Tutaj zakładam, że masz skonfigurowane GitRepository w Flux, które wskazuje na twoje repozytorium i gałąź.
      chart: ./HelmCharts/prometheus_prod/prometheus
      sourceRef:
        kind: GitRepository
        name: kubeservices-config  # Zmień na nazwę GitRepository w Flux, które wskazuje na twoje repozytorium
        namespace: flux-system
  values:
    prometheus:
      server:
        persistentVolume:
          existingClaim: "test-claim"
        service:
          type: NodePort
          nodePort: 32000
      serverFiles:
        prometheus.yml:
          scrape_configs:
            - job_name: 'jenkins'
              metrics_path: '/prometheus'
              static_configs:
                - targets: ['3.250.167.70:8080']

