apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prometheus-custom
  namespace: staging
spec:
  interval: 1m
  chart:
    spec:
      chart: ./HelmCharts/prometheus_prod
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    prometheus:
      alertmanager:
        enabled: false
      server:
        persistentVolume:
          existingClaim: "prometheus-claim"
        service:
          type: NodePort
          nodePort: 30010
      serverFiles:
        prometheus.yml:
          scrape_configs:
            - job_name: 'jenkins'
              metrics_path: '/metrics'
              static_configs:
                - targets: ['jenkins.trainingnotes.fit']
            - job_name: 'grafana'
              metrics_path: '/metrics'
              static_configs:
                - targets: ['grafana.trainingnotes.fit']
            - job_name: 'postgresql'
              metrics_path: '/metrics'
              static_configs:
                - targets: ['postgresql-metrics.trainingnotes.fit']
            - job_name: 'memcached'
              metrics_path: '/metrics'
              static_configs:
                - targets: ['memcached-metrics.trainingnotes.fit']
            - job_name: 'rabbitmq'
              metrics_path: '/metrics'
              static_configs:
                - targets: ['rabbitmq-metrics.trainingnotes.fit']
