apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: rabbitmq-custom
  namespace: staging
spec:
  interval: 1m
  chart:
    spec:
      chart: ./HelmCharts/rabbitmq_prod
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    rabbitmq:
      persistence:
        enabled: false
      service:
        type: NodePort
        ports:
          amqp: "30013"
          amqpTls: "31014"
          dist: "30015"
          manager: "30016"
          epmd: "30017"
          metrics: "30018"
      metrics:
        enabled: true
