apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: sonarqube-custom
  namespace: staging
spec:
  interval: 1m
  chart:
    spec:
      chart: ./HelmCharts/sonarqube_prod
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    sonarqube:
      postgresql:
        enabled: true
        primary:
          persistence:
            enabled: true
            existingClaim: "sonarqube-claim"
      persistence:
        enabled: false
      service:
        type: NodePort
        nodePorts:
          http: 30011
          elastic: 30018