apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: sonarqube-custom
  namespace: staging
spec:
  interval: 1m
  chart:
    spec:
      chart: ./HelmCharts/sonarqube_prod
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    sonarqube:
      resources:
        requests:
          cpu: 2
          memory: 1024Mi
        limits:
          cpu: 2
          memory: 1024Mi
      postgresql:
        enabled: false
        primary:
          persistence:
            enabled: false
            existingClaim: "sonarqube-claim"
      externalDatabase:
        host: "192.168.58.196"
        user: bartek
        password: "bartek"
        existingSecret: ""
        database: postgresql
        port: 5432
      persistence:
        enabled: false
      service:
        type: NodePort
        nodePorts:
          http: 30011
          elastic: 30018
