artifactory:
  artifactory:
    postgresql:
      enabled: false
    artifactory:
        persistence:
          mountPath: "/var/opt/jfrog/artifactory"
          enabled: false
  postgresql:
    enabled: false
