sonarqube:
  service:
    type: NodePort
    nodePort: 32002
  persistence:
    enabled: true
    existingClaim: "sonarqube-claim"
  readinessProbe:
    enabled: false
  postgresql:
    enabled: true
    primary:
      persistence:
        enabled: true
        existingClaim: "sonarqube-claim"