localRepoConfigs:
  - type: local
    key: docker-repo-local
    packageType: docker
    baseConfig:
      modelVersion: 2
      description: Example Docker repository
      repoLayoutRef: simple-default
      includesPattern: "**/*"
    repoTypeConfig:
      archiveBrowsingEnabled: false
      blackedOut: false
      downloadRedirectConfig:
        enabled: false
      propertySetRefs: []
      checksumPolicyType: client-checksums
      priorityResolution: false
      maxUniqueSnapshots: 0
      handleReleases: true
      handleSnapshots: true
      snapshotVersionBehavior: unique
    packageTypeConfig: {}
    securityConfig:
      hideUnauthorizedResources: false
      signedUrlTtl: 90
    repoType: LOCAL
federatedRepoConfigs: []
releaseBundleRepoConfigs: []
remoteRepoConfigs: []
virtualRepoConfigs: []
